[package]
name = "sd-journal"
version = "0.1.0"
authors = ["Christian Klaue <mail@ck76.de>"]
edition = "2018"
license = "GPL-3.0-or-later"
keywords = ["systemd", "journald", "sd-journal", "journal", "sdjournal"]
#category = ["os::linux-apis", "api-bindings"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["unstable", "td_chrono"]
unstable = []
td_chrono = ["chrono"]

[dependencies]
sd-id128 = {path = "../sd-id128"}
sd-sys = {path = "../sd-sys"}
libc = "^0.2"
chrono = {version = "0.4", optional = true}
