name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always


jobs:
  test:
    name: test

    runs-on: ${{ matrix.system }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - system: "ubuntu-20.04"
            features: "--no-default-features --features \"245 td_chrono experimental\""
          - system: "ubuntu-20.04"
            features: "--no-default-features --features \"229 td_chrono experimental\""
          - system: "ubuntu-20.04"
            features: "--no-default-features --features \"td_chrono experimental\""
          - system: "ubuntu-18.04"
            features: "--no-default-features --features \"229 td_chrono experimental\""
          - system: "ubuntu-18.04"
            features: "--no-default-features --features \"td_chrono experimental\""
          - system: "ubuntu-16.04"
            features: "--no-default-features --features \"td_chrono experimental\""
    
    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt-get upgrade
    - name: install libsystemd
      run: sudo apt-get install -y libsystemd-dev
    - name: build
      run: cargo build --verbose ${{ matrix.features }}
    - name: check folder structure
      run: ls -la
    - name: current folder
      run: pwd
    - name: run special test
      run: cargo test --package sd-journal --test lib --all-features -- test_data --exact --nocapture
    - name: run tests
      run: cargo test --verbose ${{ matrix.features }}
    - name: doc test
      run: cargo doc ${{ matrix.features }}
